server:
  port: 7002

eureka:
  instance:
    # eureka服务端的实例名称
    # 单击版 hostname: localhost
    # 集群版
    hostname: eureka7002.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 单机版 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群本 指向其他Eureka服务器
      defaultZone: http://eureka7001.com:7001/eureka
#  server:
#    # 关闭自我保护机制，保证不可用时服务被及时剔除
#    enable-self-preservation: false
#    # 清理无效节点的时间间隔，默认60000毫秒
#    eviction-interval-timer-in-ms: 2000
